# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-25 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210226_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
